### ISSUE TITLE
[Emails] Store (and list) emails sent through the SMTP server

### ISSUE THREAD

**Issue by alexisbouchez** [valyentdev/software-citadel#6]
### Context

It'd be great for Software Citadel users to be able to see the list of the emails they've sent.

But also to show the email, in its text/html version.

## Example

Here is an example of what can be found at Resend.

![Capture d’écran 2024-07-05 à 17 10 47](https://github.com/valyentdev/citadel/assets/80361585/1f2da831-cad6-496c-9b9a-6ee9b74e6c25)

![Capture d’écran 2024-07-05 à 17 11 11](https://github.com/valyentdev/citadel/assets/80361585/775cd477-913b-4401-b60c-aa50e84d12c2)

### Tasks

- [ ] Add some new model (with its migration), named EmailSent for instance, storing the organization id, subject, from, to, ...
- [ ] Add some new repository
- [ ] Store every sent emails, [directly in the smtp backend](https://github.com/valyentdev/citadel/blob/c17a889662e9af093650c3d6bad870974d555da7/internal/smtp_backend/smtp_backend.go#L132) for now
- [ ] Add a new tab called "Emails", in the emails pages
- [ ] Add a `/orgs/<orgId>/mails/list` retrieving emails sent from the current org
- [ ] Add a `/orgs/<orgId>/mails/show/>mail_id>` showing a single email details

**Comment by alexisbouchez** [comment]
Moving to https://github.com/valyentdev/ferdinand
