### ISSUE TITLE
[Emails] Add a test mode

### ISSUE THREAD

**Issue by alexisbouchez** [valyentdev/software-citadel#7]
### Context

While in development, it is a common practice for developers to preview the emails that their code produces.

In these cases, the email doesn't have to be delivered to the recipient.

### Prerequisites

For this task to be completed, #6 should already be implemented.

### Tasks

- [ ] Allow to toggle a test mode
        - When browsing emails in `/orgs/<org_id>/emails/list` 
        - On the example code, in the overview page (showing how to enable the test mode)
- [ ] Add a `test_mode` field in `EmailSent` model
- [ ] Set the `test_mode` field to true
       - When the SMTP username is test
       - Use the SMTP username `test` (to enable the test mode), in the HTTP endpoint (`/api/v1/emails`) when specified in the payload
- [ ] Make sure the email isn't delivered when the test mode is enabled

**Comment by alexisbouchez** [comment]
Moving to https://github.com/valyentdev/ferdinand
